<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NoticiasEventosSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');
        $registros = [
            [
                'Titulo'             => 'ColombiaPlast 2026: Feria Internacional del Plástico en Bogotá',
                'Resumen'            => 'La principal feria de plásticos, caucho y reciclaje de la región andina regresa a Corferias con soluciones para economía circular y sostenibilidad.',
                'Contenido'          => 'ColombiaPlast es la feria internacional más importante para la industria del plástico, caucho, petroquímica, empaques y envases en la región andina, centroamericana y del Caribe. La edición 2026 se realizará del 28 de septiembre al 2 de octubre en Corferias, Bogotá. Incluye soluciones para producción sostenible, reciclado y economía circular, maquinaria e innovación tecnológica, agenda académica enfocada en sostenibilidad y competitividad, y zonas especializadas como impresión 3D y manufactura aditiva. En 2024 congregó a 39.334 visitantes y 300 expositores de 18 países.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800',
                'Tipo'               => 'Evento',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => '2026-09-28 09:00:00',
                'FechaEventoFin'     => '2026-10-02 18:00:00',
                'Ubicacion'          => 'Corferias, Bogotá, Colombia',
                'Modalidad'          => 'Presencial',
                'EnlaceEvento'       => 'https://www.colombiaplast.org/',
                'FechaPublicacion'   => '2025-01-15 10:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 1,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Investigadores colombianos desarrollan bioplásticos a partir de aguas residuales',
                'Resumen'            => 'Proyecto de Minciencias produce PHA (polihidroxialcanoatos) mediante bacterias presentes en aguas residuales, reduciendo costos y el impacto ambiental.',
                'Contenido'          => 'Investigadores colombianos, con financiamiento del Ministerio de Ciencia, Tecnología e Innovación, avanzan en la producción de polihidroxialcanoatos (PHA), un bioplástico biodegradable, a partir de microorganismos presentes en aguas residuales. El proyecto explora bacterias como Pseudomonas, Paracoccus denitrificans y Bacillus megaterium para producir PHA, que se descompone naturalmente en suelo y agua. Los investigadores desarrollan cultivos microbianos mixtos a partir de aguas residuales para reducir costos en lugar de cultivos puros que requieren condiciones estériles. El PHA tiene aplicaciones en empaques, adhesivos, cápsulas de medicamentos e implantes quirúrgicos.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://www.aguasresiduales.info/revista/noticias/investigadores-de-colombia-avanzan-en-la-obtencion-kiruW',
                'FechaPublicacion'   => '2024-03-20 09:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 1,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Semana del Plástico 2025: Conexiones estratégicas y economía circular',
                'Resumen'            => 'Acoplásticos organiza evento virtual gratuito del 9 al 13 de junio con conferencias sobre innovación, sostenibilidad y economía circular.',
                'Contenido'          => 'Acoplásticos organiza la Semana del Plástico 2025, un evento virtual gratuito del 9 al 13 de junio que reunirá a proveedores y compradores del sector. El programa incluye conferencias técnico-comerciales sobre innovación, sostenibilidad, economía circular y citas de negocios virtuales. Es una oportunidad para conectar con la industria plástica colombiana y conocer las últimas tendencias en reciclaje, bioplásticos y transformación hacia modelos circulares.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
                'Tipo'               => 'Evento',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => '2025-06-09 08:00:00',
                'FechaEventoFin'     => '2025-06-13 18:00:00',
                'Ubicacion'          => 'Virtual',
                'Modalidad'          => 'Virtual',
                'EnlaceEvento'       => 'https://www.plastico.com/noticias/semana-del-plastico-2025-conexiones-estrategicas-para-el-crecimiento-de-la-industria',
                'FechaPublicacion'   => '2025-02-01 10:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Pacto por los Plásticos traza el camino hacia economía circular en Colombia al 2030',
                'Resumen'            => 'Cempre coordina plataforma colaborativa que reúne empresas, gobierno y recicladores para acelerar la transición hacia plásticos circulares.',
                'Contenido'          => 'El Pacto por los Plásticos es una plataforma colaborativa coordinada por Cempre que busca acelerar la transición hacia la economía circular de plásticos en Colombia con meta al 2030. Reúne a empresas, gobierno, organizaciones de recicladores, academia y ONG. Sus objetivos incluyen: eliminar plásticos problemáticos e innecesarios; transformar envases a formatos reutilizables, reciclables o compostables; aumentar la tasa de reciclaje al 50%; y alcanzar 30% de contenido reciclado promedio en envases. Colombia pone más de 700.500 toneladas de envases plásticos en el mercado anual, pero solo el 3% se reincorpora en nuevos envases.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1611273426858-450f384081ca?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://cempre.org.co/pacto-por-los-plasticos-traza-el-camino-hacia-la-economia-circular-de-plasticos-en-colombia-para-el-2030/',
                'FechaPublicacion'   => '2024-11-15 12:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 1,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Esenttia inaugura planta piloto de reciclaje químico en Barrancabermeja',
                'Resumen'            => 'Colombia se convierte en pionera en Latinoamérica con reciclaje químico operativo. Proyecto ganador del Premio Portafolio 2024.',
                'Contenido'          => 'Esenttia, filial petroquímica del Grupo Ecopetrol, desarrolla el proyecto "Reciclaje químico avanzado: plástico 100% circular", ganador del Premio Portafolio 2024. Pyrcom convierte residuos plásticos en aceite pirolítico; la Refinería de Barrancabermeja produce propileno verde; Esenttia lo transforma en polipropileno circular. Colombia y Brasil son los únicos países latinoamericanos con esta tecnología operativa. El proceso reduce emisiones de CO2 en más del 40% y aborda el 70% de plásticos que actualmente no se reciclan. Alcance nacional e internacional hasta 2027.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://www.portafolio.co/innovacion/reciclaje-quimico-solucion-sostenible-a-cargo-de-esenttia-617831',
                'FechaPublicacion'   => '2024-05-22 14:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 1,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'GreenPlast 2025: Tecnología, reciclaje y sostenibilidad en Milán',
                'Resumen'            => 'Feria internacional del 27 al 30 de mayo en Italia con enfoque en procesamiento, reciclaje y reutilización de plásticos.',
                'Contenido'          => 'GreenPlast 2025 se realizará del 27 al 30 de mayo en Milán, Italia, con cerca de 200 expositores en 5.500 metros cuadrados. La feria enfatiza tecnologías de procesamiento, reciclaje y reutilización de plásticos. Incluye la conferencia internacional "Construyendo un futuro sostenible para los plásticos" e iniciativas educativas dirigidas a nuevas generaciones. Es referencia europea para la industria de plásticos sostenibles, bioplásticos y economía circular.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800',
                'Tipo'               => 'Evento',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => '2025-05-27 09:00:00',
                'FechaEventoFin'     => '2025-05-30 18:00:00',
                'Ubicacion'          => 'Milán, Italia',
                'Modalidad'          => 'Presencial',
                'EnlaceEvento'       => 'https://mundoplast.com/greenplast-2025/',
                'FechaPublicacion'   => '2025-01-20 09:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Ley 2232: Colombia prohibe plásticos de un solo uso desde julio 2024',
                'Resumen'            => 'La prohibición de bolsas, pitillos y otros productos generó una reducción del 62% en consumo de bolsas en ocho meses.',
                'Contenido'          => 'La Ley 2232 de 2022 entró en vigencia el 7 de julio de 2024 prohibiendo bolsas de punto de pago, pitillos, mezcladores, rollos de bolsas y soportes plásticos. Los resultados son contundentes: el consumo formal de bolsas cayó 62% en ocho meses. Para 2030 se prohibirán envases para líquidos, platos desechables y cubiertos plásticos. Las botellas PET de agua deben contener 50% de material reciclado en 2025 (90% para 2030). La Resolución 0803 de 2024 reglamenta la implementación y establece que los productos prohibidos deben reemplazarse por alternativas biodegradables o 100% recicladas de fuente nacional.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://www.minambiente.gov.co/documento-normativa/ley-2232-de-2022',
                'FechaPublicacion'   => '2024-07-07 00:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'VII Edición Plásticos y Economía Circular: Más allá del reciclado',
                'Resumen'            => 'Jornada de AIMPLAS en Valencia sobre ecodiseño, reutilización, refill y sistemas digitales para materiales plásticos.',
                'Contenido'          => 'AIMPLAS organiza la VII Edición de la jornada "Plásticos y Economía Circular: Más allá del reciclado", enfocada en ecodiseño, reutilización, sistemas de refill y tecnologías digitales para materiales plásticos. El evento reúne a expertos del sector para compartir experiencias y tendencias en economía circular, reutilización de envases y diseño para el reciclaje. Es una referencia en Europa para la industria de plásticos sostenibles.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800',
                'Tipo'               => 'Evento',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => '2025-02-06 09:00:00',
                'FechaEventoFin'     => '2025-02-06 18:00:00',
                'Ubicacion'          => 'Valencia, España',
                'Modalidad'          => 'Presencial',
                'EnlaceEvento'       => 'https://www.aimplas.es/jornadas/vii-edicion-plasticos-y-economia-circular/',
                'FechaPublicacion'   => '2024-12-10 10:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Industria plástica invierte US$150 millones en ampliar reciclaje en Colombia',
                'Resumen'            => 'El sector ha invertido más de US$150 millones entre 2021 y 2025, añadiendo 90.000 toneladas anuales de capacidad de procesamiento.',
                'Contenido'          => 'La industria plástica colombiana invirtió más de US$150 millones entre 2021 y 2025 para ampliar la capacidad de reciclaje, añadiendo 90.000 toneladas anuales de procesamiento y elevando el total nacional a cerca de 400.000 toneladas. Las inversiones han generado alrededor de 250.000 empleos, incluyendo recicladores de oficio. Colombia aprovecha 2,4 millones de toneladas de residuos mediante una red de más de 74.000 recicladores en 250 municipios. El plástico es el segundo material con mayor aprovechamiento (935.106 toneladas, 38,92% del total).',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://forbes.co/2025/03/11/sostenibilidad/industria-plastica-ha-invertido-us-150-millones-en-reciclaje',
                'FechaPublicacion'   => '2024-06-05 11:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Factorías bacterianas: bioplásticos PHA a partir de plásticos convencionales',
                'Resumen'            => 'Investigadores del CSIC diseñan bacterias que transforman PET y derivados de lignina en PHA, el mayor rendimiento reportado hasta la fecha.',
                'Contenido'          => 'Investigadores del CSIC han diseñado cepas de la bacteria Pseudomonas putida capaces de transformar residuos plásticos (PET) y derivados de lignina directamente en polihidroxialcanoatos (PHA) mediante biología sintética. El avance logra la mayor producción de PHA a partir de PET jamás reportada. Los PHA son bioplásticos totalmente biodegradables que se descomponen en diferentes ambientes, incluyendo medios marinos. Este enfoque innovador permite cerrar el ciclo del plástico: transformar residuos plásticos en nuevos materiales biodegradables. El mercado de bioplásticos se espera que alcance 57.000 millones de dólares en 2032.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1582719478250-c89c6d9dba28?w=800',
                'Tipo'               => 'Noticia',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://www.csic.es/es/actualidad-del-csic/disenan-factorias-bacterianas-para-producir-bioplasticos-partir-de-plasticos-convencionales',
                'FechaPublicacion'   => '2024-08-15 09:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 0,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
            [
                'Titulo'             => 'Minciencias lanza Clúster Colombiano de Bioplásticos',
                'Resumen'            => 'Primera iniciativa de su tipo en Latinoamérica reúne sector privado, público y academia para impulsar el mercado de bioplásticos.',
                'Contenido'          => 'El Ministerio de Ciencia, Tecnología e Innovación y el Programa de Plásticos Circulares de las Américas (CPAP), financiado por la Unión Europea, firmaron una alianza para crear el Clúster Nacional de Bioplásticos de Colombia, pionero en Latinoamérica. El clúster busca facilitar un grupo de trabajo de triple hélice (sector privado, público y academia) para propiciar el intercambio de innovaciones, mejores prácticas y cooperación técnica y comercial. Se alinea con la Misión Nacional de Bioeconomía, que busca desarrollar más de 500 bioproductos de alto valor agregado para 2030, incluyendo bioplásticos derivados del aprovechamiento sostenible de la biodiversidad colombiana.',
                'ImagenUrl'          => 'https://images.unsplash.com/photo-1569163138391-4d1b8cf24d2a?w=800',
                'Tipo'               => 'Anuncio',
                'CategoriaId'        => null,
                'FechaEventoInicio'  => null,
                'FechaEventoFin'     => null,
                'Ubicacion'          => null,
                'Modalidad'          => null,
                'EnlaceEvento'       => 'https://www.minciencias.gov.co/sala_de_prensa/minciencias-firma-alianza-para-desarrollar-y-lanzar-el-cluster-colombiano',
                'FechaPublicacion'   => '2022-07-07 10:00:00',
                'FechaExpiracion'    => null,
                'EsDestacado'        => 1,
                'EsPublico'          => 1,
                'Estado'             => 'Publicado',
                'FechaCreacion'      => $now,
                'FechaModificacion'  => null,
            ],
        ];

        $this->db->table('noticias_eventos')->insertBatch($registros);
    }
}
